
PROGRAM FISOC_main

  USE ESMF

  USE FISOC_parent_mod, ONLY : FISOC_parent_register

  IMPLICIT NONE

  ! return code (generated by ESMF) and user return code (generated by user 
  ! code and passed through ESMF) 
  INTEGER :: rc, urc

!*** explicit type declarations:

!*** grids

! ***input file (namelist) with run parameters (temporal control and coupling options?)
! ***where is clock actually advanced? or keep multiple clocks for checking?

  ! Timekeeping
  TYPE(ESMF_Clock)        :: FISOC_clock
  INTEGER                 :: ts_ocn_sec, ts_ice_sec, ts_ratio
  INTEGER                 :: start_year, end_year, start_month, end_month
  TYPE(ESMF_TimeInterval) :: ts_ocn, ts_ice
  TYPE(ESMF_Time)         :: startTime, endTime
  TYPE(ESMF_Alarm)        :: alarm_ocn, alarm_ice
  LOGICAL                 :: tight_coupling

!***explain...
  TYPE(ESMF_GridComp)     :: FISOC_parent 
  TYPE(ESMF_State)        :: FISOC_dummy_state



! some things ESMF offers:
! logging (you don't need to create a log, ESMF will create a default log on initialize, 
! but you can create further logs using ESMF if you want) 
! regridding
! clocks and alarms

!*** actual code:

!*** what calendar? 360 day?
  ! initialize ESMF framework
  CALL ESMF_Initialize(defaultCalKind=ESMF_CALKIND_GREGORIAN, &
       defaultlogfilename="FISOC.Log", &
       logkindflag=ESMF_LOGKIND_MULTI, rc=rc)
  IF (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, &
       line=__LINE__, file=__FILE__)) THEN
     CALL ESMF_Finalize(endflag=ESMF_END_ABORT)
  END IF
!***does parent have access to child import/export states?
!*** global params:
! ***alarms:
! FISOC_ice (periodic)
! FISOC_ocn_ss event activated.  ocean steady state alarm.  turn on when geometry has 
! changed a lot, turn off when ocn steady state is reached (set time or monitoring 
! climatology?)

!***read input file

!*** create parent grid component (not sure what this is for!? do we really need it?)
!??? how does the parent grid relate to the child grids?
  ! Create the top level Gridded Component.
  FISOC_parent = ESMF_GridCompCreate(name="FISOC parent gridded component", rc=rc)
  IF (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, &
       line=__LINE__, file=__FILE__)) &
       CALL ESMF_Finalize(endflag=ESMF_END_ABORT)

!*** register parent 
  CALL ESMF_GridCompSetServices(FISOC_parent, FISOC_parent_register, &
       userRc=urc, rc=rc)
  PRINT *, "FISOC parent SetServices finished, rc =", rc, urc
  IF (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, &
       line=__LINE__, file=__FILE__)) &
       CALL ESMF_Finalize(endflag=ESMF_END_ABORT)
  
!------------------------------------------------------------------------------
! FISOC time model 
! 
! FISOC runs one clock which increments with the ocean timestep. The ice 
! timestep must be a multiple of the ocean timestep.  An ocean alarm is used 
! to indicate whether the ocean model should be run.  The alarm is event driven 
! and is set to always on for tightly coupled simulations.  An ice alarm is 
! used to indicate whether the ice model should be run.  This is a periodic 
! alarm.
!
! ***we could also have a clock in each component and do some checks that the 
! clocks are on the same time?
!
! ***loose coupling needs more thought - logical switch sent to FISOC_proc state?
!
! FISOC time related variables:
! FISOC_clock          the main FISOC clock
! alarm_ice            the (periodic) alarm for the ice model 
! alarm_ocn            the (event driven) alarm for the ocean model
! tight_coupling (config) whether tight coupling (always call ocean) or loose 
!                      coupling (call ocean after large geometry change) 
! ts_ocn_sec (config)  ocean timestep in seconds
! ts_ratio   (config)  timestep ratio 
! ts_ice_sec           ice timestep in seconds  (=ts_ocn_sec*ts_ratio)
! ts_ocn               ocean timestep in ESMF format
! ts_ice               ice timestep in ESMF format
! start_year  (config) start and end dates for FISOC simulation
! start_month (config) ...
! end_year    (config) ...
! end_month   (config) ...
!
! variables marked (config) are set in the FISOC_config file.

!------------------------------------------------------------------------------
  ts_ocn_sec = 300
  ts_ratio = 10
  ts_ice_sec = ts_ocn_sec * ts_ratio
  start_year = 2010
  end_year   = 2010
  start_month= 1
  end_month  = 2
  tight_coupling = .TRUE.

!------------------------------------------------------------------------------
! setting up clocks and alarms
!
  CALL ESMF_TimeIntervalSet(ts_ocn, s=ts_ocn_sec, rc=rc)
  IF (rc /= ESMF_SUCCESS) CALL ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

  CALL ESMF_TimeIntervalSet(ts_ice, s=ts_ice_sec, rc=rc)
  IF (rc /= ESMF_SUCCESS) CALL ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

  CALL ESMF_TimeSet(startTime, yy=start_year, mm=start_month, dd=1, rc=rc)
  IF (rc /= ESMF_SUCCESS) CALL ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

  CALL ESMF_TimeSet(endTime, yy=end_year, mm=end_month, dd=1, rc=rc)
  IF (rc /= ESMF_SUCCESS) CALL ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

  FISOC_clock = ESMF_ClockCreate(ts_ocn, startTime, stopTime=endTime, &
       name="FISOC main clock", rc=rc)
  IF (rc /= ESMF_SUCCESS) CALL ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

  alarm_ocn = ESMF_AlarmCreate(clock=FISOC_clock, name="alarm_ocn", &
       ringTime=startTime, rc=rc)
  IF (rc /= ESMF_SUCCESS) CALL ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

  alarm_ice = ESMF_AlarmCreate(clock=FISOC_clock, name="alarm_ice", &
       ringTime=startTime, &
       ringInterval=ts_ice, rc=rc)
  IF (rc /= ESMF_SUCCESS) CALL ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
  
!***turn on ocn alarm if tight coupling

!*** create grid 
! ??? what grid is this?  used by child or parent grid components? is parent grid meaningless?

!------------------------------------------------------------------------------
!***  Create and initialize a dummy State to use for both import and export.
!??? dummy for parent, one state for both import and export. do we really need this?
  FISOC_dummy_state = ESMF_StateCreate(Name="FISOC_dummy_state", rc=rc)
  IF (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, &
       line=__LINE__, file=__FILE__)) &
       CALL ESMF_Finalize(endflag=ESMF_END_ABORT)

!------------------------------------------------------------------------------
! The main bit: initialize, run and finalize FISOC_parent (the parent calls 
! all child components).
  CALL ESMF_GridCompInitialize(FISOC_parent, &
       importState=FISOC_dummy_state, exportState=FISOC_dummy_state, &
       clock=FISOC_clock, userRc=urc, rc=rc)
  IF (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, &
       line=__LINE__, file=__FILE__)) &
       CALL ESMF_Finalize(endflag=ESMF_END_ABORT)
  
  CALL ESMF_GridCompRun(FISOC_parent, &
       importState=FISOC_dummy_state, exportState=FISOC_dummy_state, &
       clock=FISOC_clock, userRc=urc, rc=rc)
  IF (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, &
       line=__LINE__, file=__FILE__)) &
       CALL ESMF_Finalize(endflag=ESMF_END_ABORT)

 
  CALL ESMF_GridCompFinalize(FISOC_parent, &
       importState=FISOC_dummy_state, exportState=FISOC_dummy_state, &
       clock=FISOC_clock, userRc=urc, rc=rc)
  IF (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, &
       line=__LINE__, file=__FILE__)) &
       CALL ESMF_Finalize(endflag=ESMF_END_ABORT)
  
!------------------------------------------------------------------------------
!***destroy clock and both alarms and grid component(s)

!*** destroy stuff and finalize ESMF

  CALL ESMF_Finalize()

END PROGRAM FISOC_main
