
MODULE FISOC_Elmer_types
  
  IMPLICIT NONE
  
  INTEGER, PARAMETER :: ELMER_ELEMENT_NODAL            = 101
  INTEGER, PARAMETER :: ELMER_ELEMENT_LINE_LINEAR      = 202
  INTEGER, PARAMETER :: ELMER_ELEMENT_LINE_QUADRAT     = 203
  INTEGER, PARAMETER :: ELMER_ELEMENT_LINE_CUBIC       = 204
  INTEGER, PARAMETER :: ELMER_ELEMENT_TRIANGLE_LINEAR  = 303
  INTEGER, PARAMETER :: ELMER_ELEMENT_TRIANGLE_QUADRAT = 306
  INTEGER, PARAMETER :: ELMER_ELEMENT_TRIANGLE_CUBIC   = 310
  INTEGER, PARAMETER :: ELMER_ELEMENT_QUADRIL_BILINEAR = 404
  INTEGER, PARAMETER :: ELMER_ELEMENT_QUADRIL_QUADRAT  = 408
  INTEGER, PARAMETER :: ELMER_ELEMENT_QUADRIL_QUADRAT2 = 409
  INTEGER, PARAMETER :: ELMER_ELEMENT_QUADRIL_CUBIC    = 412
  INTEGER, PARAMETER :: ELMER_ELEMENT_TETRA_LINEAR     = 504
  INTEGER, PARAMETER :: ELMER_ELEMENT_TETRA_QUADRAT    = 510
  INTEGER, PARAMETER :: ELMER_ELEMENT_PYRAMID_LINEAR   = 605
  INTEGER, PARAMETER :: ELMER_ELEMENT_PYRAMID_QUADRAT  = 613
  INTEGER, PARAMETER :: ELMER_ELEMENT_WEDGE_LINEAR     = 706
  INTEGER, PARAMETER :: ELMER_ELEMENT_WEDGE_QUADRAT    = 715
  INTEGER, PARAMETER :: ELMER_ELEMENT_HEXAHED_TRILIN   = 808
  INTEGER, PARAMETER :: ELMER_ELEMENT_HEXAHED_QUADRAT  = 820
  INTEGER, PARAMETER :: ELMER_ELEMENT_HEXAHED_QUADRAT2 = 827

END MODULE FISOC_Elmer_types
